version: '3'

services:

    # redis:
    #     image: redis:latest

    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        # links:
        #     - redis
        env_file:
        - ./.env
        # volumes:
        #     - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        # command: python -m app.run_celery_worker
        # command: [celery, worker, --app=app.run_celery_worker, --pool=gevent, --concurrency=20, --queues=minio, --loglevel=INFO]
        command: [celery, worker, --app=app.run_celery_worker, --pool=gevent, --concurrency=20, --loglevel=INFO]
        # links:
        #     - redis
        # env_file:
        # - ./.env
        user: pyuser
        volumes:
            - ./.env:/app/.env:ro

